dataDriver: DataDriver.cpp Sorts.h bubbleSort.cpp insertionSort.cpp mergeSort.cpp quickSort.cpp selectionSort.cpp
	g++ -g   DataDriver.cpp -o dataDriver
testDriver: TestDriver.cpp Sorts.h bubbleSort.cpp insertionSort.cpp mergeSort.cpp quickSort.cpp selectionSort.cpp
	g++ -g  TestDriver.cpp -o testDriver
clean:
	rm -f *.o *~ dataDriver testDriver
